In [1]:
import pandas as pd

df1 = pd.read_csv('/Users/john.tung/Downloads/Ni/原始csv/20210101_20210131_财务渠道_代理.csv', encoding="gb2312")
print(len(df1))
df1.head()

1775

      所属代理  状态   细分类型  使用人数     次数           金额        反应时间    总次数       成功率
0  xixi899  成功  银行卡转账  1955  28645  65921659.00  185.437284  39901  0.717902
1    admin  成功  银行卡转账  1465  24792  64167114.98  211.003066  38817  0.638689
2  seo5002  成功  银行卡转账   739  16164  53228681.99  204.470799  21868  0.739162
3  Yaoqing  成功  银行卡转账  1490  19722  44067149.99  195.993104  29121  0.677243
4  seo3000  成功  银行卡转账   515  10738  38113571.99  182.354070  14818  0.724659

In [2]:
df1.to_csv('/Users/john.tung/Downloads/Ni/處理過的csv/20210101_20210131_财务渠道_代理.csv', encoding='utf_8_sig', index=False)

In [2]:
df2 = pd.read_csv('/Users/john.tung/Downloads/Ni/原始csv/20210101_20210131_财务渠道_名单.csv', encoding="gb2312")
df2.head()

   状态          用户名   细分类型   次数         金额        反应时间  总次数       成功率
0  成功  lijia850330  银行卡转账  284  6923800.0  141.211268  363  0.782369
1  成功    lxg933131  银行卡转账  235  4623384.0  130.782979  335  0.701493
2  成功    qwert2019  银行卡转账  160  4530745.0   91.912500  193  0.829016
3  成功    w25342486  银行卡转账  134  4102974.0  143.507463  184  0.728261
4  成功    daiwei811  银行卡转账  186  4092679.0  183.172043  228  0.815789

In [3]:
df2.to_csv('/Users/john.tung/Downloads/Ni/處理過的csv/20210101_20210131_财务渠道_名单.csv', encoding='utf_8_sig', index=False)

In [4]:
df3 = pd.read_csv('/Users/john.tung/Downloads/Ni/原始csv/20210101_20210131_财务渠道_概况.csv', encoding="gb2312")
df3.head()

,日期,状态,细分类型,使用人数,次数,金额,反应时间,总次数,成功率
0,2021-01-30,成功,银行卡转账,7909,16761,36157455.99,228.402184,39134,0.428298
1,2021-01-31,成功,银行卡转账,7735,16718,35923252.88,218.041991,30658,0.545306
2,2021-01-29,成功,银行卡转账,7417,15972,35751501.00,229.976459,33696,0.474003
3,2021-01-24,成功,银行卡转账,6578,13865,30979847.00,242.490299,22837,0.607129
4,2021-01-28,成功,银行卡转账,6469,13758,31100585.96,207.320105,23391,0.588175

In [5]:
df3.to_csv('/Users/john.tung/Downloads/Ni/處理過的csv/20210101_20210131_财务渠道_概况.csv', encoding='utf_8_sig', index=False)